# Generated by Django 4.1.5 on 2023-01-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=50)),
                ('card_subtype', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
